### ISSUE TITLE
god of war collection 

### ISSUE THREAD

**Issue by manofsteel2017** [SilicaAndPina/TropHAX#12]
doesn't work

**Comment by SilicaAndPina** [comment]
ret code?

**Comment by essegrev** [comment]
As a result of verification, GoW1 worked but GoW2 Plugin error (ret 8055160x).
Details look at #7

**Comment by essegrev** [comment]
I tried it a couple of times and it worked. Sorry.

**Comment by SilicaAndPina** [comment]
Please give me the ur0:user/00/trophy/data/NPWR folders for the game.
and i can make it work.

**Comment by 4rchitect** [comment]
NPWR05244_00 - God of war I
NPWR05283_00 - God of war II

@essegrev said it is working.

**Comment by SilicaAndPina** [comment]
>_> I meant the actural folders themselves. arg you know what just use trophyPatcher .

**Comment by SilicaAndPina** [comment]
game confirmed working
