### ISSUE TITLE
hello ,Sword art online HF (CN) dont work and other  question

### ISSUE THREAD

**Issue by YZblade1020** [SilicaAndPina/TropHAX#15]
Sword art online HF 1.0-1.04 don't work   (No response)
and other game unlock trophy three,must Close game .otherwise (ret 80551604)

**Comment by SilicaAndPina** [comment]
SAO -HF- Patch:
https://stack.gigafyde.nl/s/PoMlsDQQ1ySBFYF

simply install this maidump, (lufterausers) and use tropHAX to unlock all..
it will now unlock trophys for Sao HF.

**Comment by YZblade1020** [comment]
It is really very grateful
nice good job
i love you

2018-02-01 17:41 GMT+08:00 Silica <notifications@github.com>:

**Comment by SilicaAndPina** [comment]
NP :)

**Comment by YZblade1020** [comment]
Hey buddy.First of all thank you very much for your English version of SAO
Can help me, try the CN version of it

2018-02-01 18:59 GMT+08:00 Silica <notifications@github.com>:
