### ISSUE TITLE
SummonNight6 can not work

### ISSUE THREAD

**Issue by swclyt** [SilicaAndPina/TropHAX#16]
SummonNight6(version 1.03) can not work, press select+start cannot show up the title and message

**Comment by SilicaAndPina** [comment]
Please give me the ur0:trophy/00/NPWR and ux0:app/titleid/sce_sys/trophy folders for the game.
and i can make a compadiblity patch.

**Comment by 4rchitect** [comment]
Well this one has two trophy folders:
NPWR10197_00 - This one has trophies in japonese, chinese and english.
NPWR12871_00 - This one has only trophies in english.

**Comment by SilicaAndPina** [comment]
T-TWO TROPHY FOLDERS? WHAAT..

also. when i say to give me the folders i mean like litterally send me the files >_>

**Comment by SilicaAndPina** [comment]
Duplicate and Patch reelased see #7
