### ISSUE TITLE
Infinita Strada Hana Does not work with TropHAX

### ISSUE THREAD

**Issue by Shinigati** [SilicaAndPina/TropHAX#17]
Basically the title, i have tried using TropHAX with this game but it does not seem to work, as i understand only 90% of games work but figured i'd report this bug anyway so it can be fixed in the future.

TitleID: PCSH-00278

**Comment by SilicaAndPina** [comment]
Please give me the ur0:user/00/trophy/data/NPWR folders for the game.
and i can make it work.

**Comment by 4rchitect** [comment]
NPWR11097_00

**Comment by SilicaAndPina** [comment]
i mean the actural folders . . .

**Comment by Shinigati** [comment]
Thanks for the response, i'll upload the files as soon as i can.
