### ISSUE TITLE
Issue with the Game Volume

### ISSUE THREAD

**Issue by Tsuukasa-R** [SilicaAndPina/TropHAX#2]
Tried this plugin with Volume. This Game normally plays fine. But with this plugin enabled the Game dont boot anymore. 
Stays infinitly at the Start Picture screen. And if i then Close the game i cant boot anything else and everything that are in folder Bubbles is gone. I need then to do a hard reset (Hold Power Button 20 Sec) because if i want to shutdown the LED blinks blue the whole time and nothing happens.

I read somewhere that Unity Games are making problems with this plugin. I think this game was made with Unity.. Hope this can be fixed

**Comment by SilicaAndPina** [comment]
so your entire vita is crashing?

**Comment by Tsuukasa-R** [comment]
If i start the game no. It just start the game (I can use home button etc).
But after i startet the game and closed it then, every i written will happen. Never expierienced anything like that

**Comment by Pocxki** [comment]
I own the game myself and i'll have some test on volume when i get home. I'll inform the team later on with results.

**Comment by SilicaAndPina** [comment]
that honestly is the weridst thing ive heard of

**Comment by Tsuukasa-R** [comment]
@pocxki that would be great. Got the maidump version of the game (Nonpdrm Version was never released).

**Comment by SilicaAndPina** [comment]
um try downloading the suprx again
i remember mai messing up some shit initally so we did a stealth update.

**Comment by Tsuukasa-R** [comment]
i downloaded the plugin again but same problem...

**Comment by SilicaAndPina** [comment]
ook so thats not the issue,

**Comment by Tsuukasa-R** [comment]
Havent u say unity game are a problem ? Maybe thats why ? Other than that i dont know why its actin so weird :/

**Comment by SilicaAndPina** [comment]
we supposedly fixed unity .-.

**Comment by Tsuukasa-R** [comment]
Thats really strange....
Then i we have to wait for  Pocxki  for testing his version of the game :/

**Comment by SilicaAndPina** [comment]
yep
also the error ur describing seems weird,

**Comment by Tsuukasa-R** [comment]
I can confirm that the same thing happens on Deemo the Last Recital, which is also a unity game.
Tested this on the Asia English Retail Card of the game

**Comment by SilicaAndPina** [comment]
maybe unity isnt fully fixed yet?
possibly different versions of unity

**Comment by Tsuukasa-R** [comment]
This could be. Tested this plugin on 4 Games now, 2 worked (which i think arent unity Games) and 2 which didnt worked and they where unity games. Maybe you could look into it. Other than that i dont know

**Comment by Pocxki** [comment]
Just tested volume, unlocks 100% no errors or crashes...
so it's a problem with your game or settings, not the plugin

**Comment by Pocxki** [comment]
tested on PCSB00827

**Comment by Tsuukasa-R** [comment]
Cant find anything about PCSB00827 in google. But what version do you have ? Vpk ? Maidump? Nonpdrm ?
Maybe its maidump whats causing the probem. On the other side this cant be since i have the same problem with Deemo which is on my cart...

**Comment by Pocxki** [comment]
That's actually a MAI dump from my original game.
![volume_working](https://user-images.githubusercontent.com/28675941/31092977-728d594c-a7b0-11e7-9471-22e53bcec016.jpg)

**Comment by Pocxki** [comment]
![schermafdruk van 2017-10-02 20-30-49](https://user-images.githubusercontent.com/28675941/31093022-a95774da-a7b0-11e7-8167-90da8d83af38.png)

**Comment by Pocxki** [comment]
I can't test Deemo, since i don't own the game, unless you can link me somehow.

**Comment by SilicaAndPina** [comment]
Demos dont have trophys
