### ISSUE TITLE
Select trophies by name

### ISSUE THREAD

**Issue by Rufis01** [SilicaAndPina/TropHAX#9]
It shouldn't be too hard to implement a trophies selection by name instead of by ID.

**Comment by Rufis01** [comment]
Oh, I see what you did in the code. Now I realize it's a bit more difficult to implement.

**Comment by prototye76** [comment]
it is better when you unlock them by name

**Comment by essegrev** [comment]
If it is possible to implement it, what would you do if you were a trophy name in a language other than English?

**Comment by Nkekev** [comment]
Answered here
https://github.com/SilicaAndPina/TropHAX/issues/8

**Comment by SilicaAndPina** [comment]
hmm youd need ascii encoding correct?

i could convert katakana / hiragana to romaji fairly easy but what if it uses kanji hmm this is alot more difficult to convert programically..

**Comment by Nkekev** [comment]
yes i think we will have this issue we need to implement these characters...

**Comment by Rufis01** [comment]
Can't you just read 'em from the database?

**Comment by SilicaAndPina** [comment]
no access from a .suprx..
